---
version: '3'
services:
  sourceDB:
    image: debezium/postgres:13
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=confluent 
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=testdb
      - TZ=Asia/Seoul
    volumes:
      - ./data:/var/lib/postgresql/data
